# Generated by Django 3.2.9 on 2021-12-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_category_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(to='recipe.Category'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.TimeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_time',
            field=models.TimeField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
