# Generated by Django 3.2.9 on 2021-12-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20211210_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.TimeField(blank=True),
        ),
    ]
