# Generated by Django 3.2.9 on 2021-12-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_remove_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(to='recipe.Category'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_time',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
