# Generated by Django 3.2.9 on 2021-12-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20211210_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ManyToManyField(blank=True, to='recipe.Category'),
        ),
    ]
